server:
  port: 9002

spring:
  application:
    name: user-service
  cloud:
    compatibility-verifier:
      enabled: false
  sql:
    init:
      platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5434/microservicedb
    username: postgres
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true