server:
  port: 8017

# Email Configuration
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: riskigalangsaputra@gmail.com
    password: fsopjccalpmffinl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: email-service

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      channel-name: emailSender

